% This script will takew the imported onset times from an csv file and generate vectors of different
% lengths for each column variable

% clears all variables in the workspace
clear

% string array that contains the names of the files to process without the file extension
subjects = char('PatientID 1', 'PatientID 2', 'PatientID 3', 'PatientID 4', 'PatientID 5', 'PatientID 6', 'PatientID 7', 'PatientID 8', 'PatientID 9');
% variable holds file extention
fileExt = '.csv';
% path to the output location
outputPath = 'C:\Documents and Settings\Steven Lacey\Desktop\jx0303_n=9 Onset Times\';

% loop through the number of subjects in subjects array
% this is equivalent to asking how many rows are in the array
for i = 1:size(subjects,1);
    % set dummy equal to the data structure generated by the import function
    dummy = IMPORTDATA(strcat(subjects(i,:), fileExt), ',');
    % loop through each of the columns
    for k = 1:size(dummy.colheaders, 2);
        % set temp variable to the value in dummy.colheaders
        % .colheaders references one of the fields in the dummy structure
        % .colheaders is a cell array
        % to extact the values held in this cell array
        % refrence the element with curly braces (i.e., {k}) 
        temp = dummy.colheaders{k};
        % set temp1 to a string containing the code referencing the 
        % corresponding column of data in dummy.data
        % eliminate any 0's in the column by specifying that we only 
        % want rows that have values greater than 0
        temp1 = '= dummy.data(find(dummy.data(:,k)>0),k)';
        % concatenate temp & temp1
        temp = strcat(temp, temp1);
        % evaluate it--treats the strings as variables/code--not just string
        % sets the column name to a variable name and sets the contents of that
        % vartiable to a double array containing the relevant onset times
        eval(temp);
    end;
    % save the data in the ouputPath/subject name file
    % 'Run*' includes all variables from the workspace that begin with Run
    % this leaves i, k, and dummy that are needed to run this script
    save (strcat(outputPath, subjects(i,:)), 'Run*');
end