#!/bin/tcsh -f

if ( $# == 0 ) then
	echo ""
	echo "USAGE:	renameimg oldname newname start_file number_of_files"
	echo ""
	echo "multiple rename of analyze format files that are numbered 001 through xxx"
	echo "for example,"
	echo ""
	echo "renameimg fmri somename 1 350"
	echo ""
	echo "would rename the fmri001.img (.hdr too) through fmri350.img  files to somename001.img through somename350.img"
	echo "Note. If you only give two arguments, then it only renames one file and it's header"
	echo ""
	exit
endif


set oldroot=$1
set newroot=$2
set t=$3
set lastfile=$4

if ( $# == 2 ) then
	echo "moving ... "${oldroot}" to "${newroot}
	mv ${oldroot}.img ${newroot}.img	
	mv ${oldroot}.hdr ${newroot}.hdr	
	
	exit
endif



while  ($t <= $lastfile) 
	### figure out the zero chars in the number
	if ( $t < 10 ) then
		set zs="00"
		
	else if ( $t < 100 ) then
		set zs="0"
	else
		set zs=""
		
    	endif
	##########

	echo "moving ... "$oldroot$zs$t" to "$newroot$zs$t
	mv $oldroot$zs$t.img $newroot$zs$t.img	
	mv $oldroot$zs$t.hdr $newroot$zs$t.hdr	

	set t=`expr $t + 1`
end

