D = struct(...
          'DesName','Two sample t-test (no constant term)',...
          'n',    [Inf 2 1 1],    'sF',{{'obs','group','',''}},...
          'Hform',                'I(:,2),''-'',''group''',...
          'Bform',                '[]',...
          'nC',[0,0],'iCC',{{8,8}},'iCFI',{{1,1}},...
          'iGXcalc',[-1,2,3],'iGMsca',[1,-9],'GM',[],...
          'iGloNorm',9,'iGC',12,...
          'M_',struct('T',[-Inf,0,0.8*sqrt(-1)],'I',Inf,'X',Inf),...
          'b',struct('aTime',1))

         spm_spm_ui('CFG',D)
         