#! /bin/tcsh
if ($#argv < 1) then
  exit 1
else
  set exptname = $argv[1]
  echo working on subject $exptname
endif
set mdir = "/export/data/analyzed/tor/Class/$exptname"
cd $mdir
pwd
matlab << EOF >& log.txt
        addpath /export/apps/spm99_macosx
        addpath /home/twager/scripts
        scnlab_coreg_anat2funct('anatomy/esT1_s5.img','scan1/firstTR/refVol.img');
        quit
EOF
echo cogreg finished for subject $exptname
