function [sphere]=find_sphere(xyzmm,radius,SPM,VOL)
% [sphere]=find_sphere(xyzmm,radius,SPM,VOL)
% VOL should contain VOX (voxel sizes)

Q       = ones(1,size(SPM.XYZmm,2));
vsc     = [1 1 1];                              %-Voxel size scaling for FWHM
D=radius;
SPACE='Sphere';

j     = find(sum((SPM.XYZmm - xyzmm*Q).^2) <= D^2);
D     = D./VOL.VOX;
S     = (4/3)*pi*prod(D);

fprintf('%0.1fmm sphere centered at [%.0f,%.0f,%.0f]: %d voxels\n',radius, xyzmm(1),xyzmm(2),xyzmm(3),size(j,2));

sphere=struct(...
  'XYZ',    SPM.XYZ(:,j),...
  'XYZmm',  SPM.XYZmm(:,j),...
  'Z',      0.0,...
  'S',      S, ...
  'full_clust_size', 0,...
  'clust_p_corr',    0.0,...
  'vox_p_corr',    0.0,...
  'center', xyzmm ...
);
