#! /bin/tcsh
# Function: justAnatom
#
# Modified by Christopher Currie, 3 / 2 / 02

# FUNCTION: justAnatom subjectcode
#           where subjectcode is a string, ow1, ow2, ... , ow8 (don't quote the string input)
#
# NOTES:  
# mdir is the subject directory for preprocessed data, i.e., ow1, ow2, ... , ow8
# img has names of 4-D images, one for each run
# images for each run are saved in mdir/scan1, scan2, etc.

echo $SHELL

if ($#argv < 1) then
  echo please type in: process_subject sidcode
  echo "e.g., 'justAnatom ow1'"
  exit 1
else
  set exptname = $argv[1]
  echo working on subject $exptname
endif

set mdir = "/export/data/analyzed/tor/Class/$exptname"
echo Start building anatomicals for $exptname
matlab -nodesktop -nodisplay << EOF >& $mdir/justAnatom_log.txt
          addpath /export/data/analyzed/tor/
          addpath /export/apps/spm99_macosx
          addpath /home/twager/scripts
          exptname = '$exptname/';
          outputFileBase = '/export/data/analyzed/tor/Class';

          tor_mr2an(exptname,outputFileBase)
          quit
EOF
echo Finished building anatomicals for $exptname

