#! /bin/tcsh
#      
if ($#argv < 1) then
  echo "$0 subjcode"
  echo "please type in: process_subject sidcode "
  echo "sidcode is subject id, e.g. ow1"
  exit 1
else
  set exptname = $argv[1]
  echo $exptname
endif

      set mdir = "/export/data/analyzed/tor/Class/$exptname"
      cd $mdir

      set d = `ls r?.img`
      echo Found 4D Images: $d
      foreach img ( $d )  
              set inname=`echo $img | cut -f1 -d'.'`
              set aname = a$inname
              set runname = `echo $img | cut -f2 -d'r' | cut -f1 -d'.'`
              # slicetimer -i $inname --out=$aname -r 2.0 --ocustom=/home/twager/sliceorder.rtf
              # mv $aname.hdr scan$runname/
	      # mv $aname.img scan$runname/
	      cd scan$runname
              echo change to scan$runname
              if ( $runname == 1 ) then
                    echo ana4dto3d for $runname
	            ana4dto3d -m -v $aname.img
                    if ( -e firstTR ) then
                        echo firstTR exists . . .
                    else
                           echo making firstTR directory
                           mkdir firstTR
                    endif
                    cp ar?_0001.img refVol.img
                    cp ar?_0001.hdr refVol.hdr
                    mv refVol.* firstTR
                    rm ar?_0002.*
                    rm ar?_0003.* 
              else
                  echo ana4dto3d for $runname
                  ana4dto3d -d 3 -m -v $aname.img
              endif
              cd -
      end
      set bigfile = "avolumes.img"
      avwsplit r$bigfile
      set d = `ls -d scan?`
      echo found scan directories: $d
      @ start = 0
      set flist = `ls vol*.img`
      foreach dir ( $d )
          set dirNum=`echo $dir | cut -c 5-5`
          set trCnt = `ls -l scan$dirNum/ar$dirNum\_????.img | grep "^-" | wc -l`
          @ end = $start + $trCnt - 1
          echo $start to $end
          @ cnt = 0
          foreach f ( $flist )
                @ cnt+=1
                 if ( $cnt >= $start && $cnt <= $end) then
                     echo changing $f to $exptname\_$dir\_$f
                     cp $f $exptname\_$dir\_$f
                     echo move $exptname\_$dir\_$f to $dir
                     mv $exptname\_$dir\_$f $dir

                     echo rename and move assoicated hdr files
                     set volname=`echo $f | cut -f1 -d'.'`
                     cp $volname.hdr $exptname\_$dir\_$volname.hdr
                     mv $volname.hdr $exptname\_$dir\_$volname.hdr $dir
                 endif
          end
          @ start = $start + $trCnt
      end
      set scan = `ls -d scan?`
      foreach dir ($scan)
              cd $dir
              tar cvf $dir\_motionCorrected3d.tar $exptname\_$dir\_vol*.*
              gzip --best $dir\_motionCorrected3d.tar
              echo moved tarred and zipped 3d aligned images to main subject directory
              mv $dir\_motionCorrected3d.tar.gz ../
              rm $exptname\_$dir\_vol*.*
              echo removing all motion corrected 3d volumes
              cd ..
      end
      rm vol*.*
