#! /bin/tcsh
# Created by Christopher Currie, 3 / 2 / 02
#
if ($#argv < 1) then
 echo "$0 subjcode"
  echo "please type in: process_subject sidcode"
  echo "sidcode is subject id, e.g. ow1"
  exit 1
else
  set exptname = $argv[1]
endif

set mdir = "/export/data/analyzed/tor/Class/$exptname"
cd $mdir/anatomy
echo Taring and zipping es anatomy files in $mdir/anatomy
tar cvf $exptname\_Anatomy.tar *.*
gzip --best $exptname\_Anatomy.tar
ls *.gz
